### PR TITLE
Applying jrob update

### PR DESCRIPTION
**Pull request by mwinata94**
Implementing suggestions from: #13

### CODE REVIEW

**Comment by jrob8577** [comment]
LGTM. Does the code "feel" better to you now? More manageable? More OO?

**Comment by mwinata94** [comment]
I guess the code is more OO now because we are splitting apart a huge class into smaller classes based on distinct responsibilities, and the code definitely feels better to manage in the long run cause we don't have to scroll up/down a huge file (~1k lines of code) to extend the services, and it's easier to refactor the templates due to the use of interface. We can just refactor the templates, and the text editor would modify all of the template calls, instead of using ctrl + f -> replace.

Teach us moar

**Comment by jrob8577** [comment]
@mwinata94 What else would you like to know?

**Comment by mwinata94** [comment]
@jrob8577 hmm, is there any design pattern thats applicable in 413 and 667 that you haven't mentioned yet or you wish you could go in more detail about? And I also enjoy pleasant surprises, so I'd like to learn some black magics if you know any.

**Pull request merged**
